DROP TABLE IF EXISTS session;
DROP TABLE IF EXISTS users;
DROP TYPE IF EXISTS platform;
DROP TYPE IF EXISTS user_status;
DROP TYPE IF EXISTS gender;
DROP TYPE IF EXISTS user_role;
DROP TYPE IF EXISTS user_type;
