CREATE TABLE default_tags (
    id SERIAL PRIMARY KEY,
    category VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);

INSERT INTO default_tags (category, name) VALUES
-- Art and Creativity
('Art and Creativity', '#Painting'),
('Art and Creativity', '#Sculpture'),
('Art and Creativity', '#Photography'),
('Art and Creativity', '#Design'),
('Art and Creativity', '#Calligraphy'),
('Art and Creativity', '#AbstractArt'),
('Art and Creativity', '#DigitalArt'),
('Art and Creativity', '#Crafting'),
('Art and Creativity', '#Illustration'),
('Art and Creativity', '#StreetArt'),
-- Technology
('Technology', '#Tech'),
('Technology', '#Innovation'),
('Technology', '#ArtificialIntelligence'),
('Technology', '#MachineLearning'),
('Technology', '#CyberSecurity'),
('Technology', '#CloudComputing'),
('Technology', '#IoT'),
('Technology', '#InternetOfThings'),
('Technology', '#Programming'),
('Technology', '#Coding'),
('Technology', '#DevOps'),
('Technology', '#Startups'),
('Technology', '#Blockchain'),
('Technology', '#Cryptocurrency'),
('Technology', '#DataScience'),
('Technology', '#5G'),
('Technology', '#BigData'),
('Technology', '#InternetOfThings'),
-- Sports
('Sports', '#Cricket'),
('Sports', '#Soccer'),
('Sports', '#WorldCup'),
('Sports', '#Formula1'),
('Sports', '#Baseball'),
('Sports', '#Hockey'),
('Sports', '#Wimbledon'),
('Sports', '#SuperBowl'),
('Sports', '#UFC'),
('Sports', '#Athletics'),
('Gaming', '#Valorant'),
('Gaming', '#CallOfDuty'),
('Gaming', '#LeagueOfLegends'),
('Gaming', '#CSGO'),
('Gaming', '#DOTA2'),
('Gaming', '#Roblox'),
('Gaming', '#AmongUs'),
('Gaming', '#GTA'),
('Gaming', '#ApexLegends'),
('Gaming', '#FIFA'),
-- Food
('Food', '#Dessert'),
('Food', '#Breakfast'),
('Food', '#Dinner'),
('Food', '#Baking'),
('Food', '#Pasta'),
('Food', '#Pizza'),
('Food', '#FoodPorn'),
('Food', '#Grilling'),
('Food', '#HomeCooking'),
('Food', '#VeganRecipes'),
-- Entertainment
('Entertainment', '#Anime'),
('Entertainment', '#Streaming'),
('Entertainment', '#Series'),
('Entertainment', '#Bollywood'),
('Entertainment', '#Awards'),
('Entertainment', '#Oscars'),
('Entertainment', '#Kpop'),
('Entertainment', '#RockMusic'),
('Entertainment', '#EDM'),
('Entertainment', '#Comedy'),
-- Famous Personalities
('Famous Personalities', '#ElonMusk'),
('Famous Personalities', '#KanyeWest'),
('Famous Personalities', '#MileyCyrus'),
('Famous Personalities', '#TaylorSwift'),
('Famous Personalities', '#MarcoAsensio'),
('Famous Personalities', '#LukaModric'),
('Famous Personalities', '#LeBronJames'),
('Famous Personalities', '#SelenaGomez'),
('Famous Personalities', '#Beyonce'),
('Famous Personalities', '#JustinBieber'),
('Famous Personalities', '#Drake'),
('Famous Personalities', '#OprahWinfrey'),
('Famous Personalities', '#JeffBezos'),
('Famous Personalities', '#BillGates'),
('Famous Personalities', '#LionelMessi'),
('Famous Personalities', '#ArianaGrande'),
('Famous Personalities', '#CristianoRonaldo'),
('Famous Personalities', '#LionelMessi'),
('Famous Personalities', '#NeymarJr'),
('Famous Personalities', '#KylianMbappe'),
('Famous Personalities', '#ErlingHaaland'),
('Famous Personalities', '#RobertLewandowski'),
('Famous Personalities', '#MohamedSalah'),
('Famous Personalities', '#HarryKane'),
('Famous Personalities', '#KevinDeBruyne'),
('Famous Personalities', '#VirgilVanDijk'),
('Famous Personalities', '#KarimBenzema'),
('Famous Personalities', '#GianluigiBuffon'),
('Famous Personalities', '#ZlatanIbrahimovic'),
('Famous Personalities', '#SergioRamos'),
('Famous Personalities', '#PaulPogba'),
('Famous Personalities', '#AntoineGriezmann'),
('Famous Personalities', '#EdenHazard'),
('Famous Personalities', '#SadioMane'),
('Famous Personalities', '#MarcusRashford'),
('Famous Personalities', '#PhilFoden'),
('Famous Personalities', '#Pedri'),
('Famous Personalities', '#AnsuFati'),
('Famous Personalities', '#JadonSancho'),
('Famous Personalities', '#DeclanRice'),
('Famous Personalities', '#JoaoFelix'),
('Famous Personalities', '#AlphonsoDavies'),
('Famous Personalities', '#TrentAlexanderArnold'),
('Famous Personalities', '#ThibautCourtois'),
('Famous Personalities', '#ManuelNeuer'),
('Famous Personalities', '#SonHeungMin'),
('Famous Personalities', '#RomeluLukaku'),
('Famous Personalities', '#FrenkieDeJong'),
('Famous Personalities', '#Gavi'),
('Famous Personalities', '#AchrafHakimi'),
('Famous Personalities', '#RiyadMahrez'),
('Famous Personalities', '#ChristianPulisic'),
('Famous Personalities', '#JoshuaKimmich'),
('Famous Personalities', '#JudeBellingham'),

-- Nature and Travel
('Nature and Travel', '#Travel'),
('Nature and Travel', '#Nature'),
('Nature and Travel', '#Adventure'),
('Nature and Travel', '#Beach'),
('Nature and Travel', '#Mountains'),
('Nature and Travel', '#Camping'),
('Nature and Travel', '#Hiking'),
('Nature and Travel', '#RoadTrip'),
('Nature and Travel', '#Wildlife'),
('Nature and Travel', '#Photography'),
('Nature and Travel', '#NationalParks'),
('Nature and Travel', '#SafariAdventure'),
('Nature and Travel', '#Backpacking'),
('Nature and Travel', '#IslandHopping'),
('Nature and Travel', '#EcoTourism'),
('Nature and Travel', '#RoadTrips'),
('Nature and Travel', '#CulturalTravel'),
('Nature and Travel', '#Sunsets'),
('Nature and Travel', '#StarGazing'),
('Nature and Travel', '#Rainforest'),
('Nature and Travel', '#SnowAdventures'),
('Nature and Travel', '#DesertSafari'),
('Nature and Travel', '#CityScapes'),
('Nature and Travel', '#HiddenGems'),
('Nature and Travel', '#TravelDiaries'),
('Nature and Travel', '#LuxuryTravel'),
('Nature and Travel', '#HistoricalSites'),
('Nature and Travel', '#CampingUnderStars'),
('Nature and Travel', '#WorldHeritageSites'),
('Nature and Travel', '#MountainClimbing'),
('Nature and Travel', '#CaveExploration'),
('Nature and Travel', '#OceanView'),
('Nature and Travel', '#ForestTrails'),
('Nature and Travel', '#HotAirBalloon'),
('Nature and Travel', '#CliffDiving'),
('Nature and Travel', '#Icebergs'),
('Nature and Travel', '#Waterfalls'),
('Nature and Travel', '#RiverRafting'),
('Nature and Travel', '#WildflowerFields'),
('Nature and Travel', '#AutumnLeaves'),
('Nature and Travel', '#VolcanoTrekking'),
('Nature and Travel', '#Lakeside'),
('Nature and Travel', '#Glaciers'),
('Nature and Travel', '#TravelBlogger'),
('Nature and Travel', '#AdventurePhotography'),
('Nature and Travel', '#CulturalHeritage'),
('Nature and Travel', '#HikingTrails'),
('Nature and Travel', '#Seaside'),
('Nature and Travel', '#Countryside'),
-- Health and Fitness
('Health and Fitness', '#Health'),
('Health and Fitness', '#Fitness'),
('Health and Fitness', '#Yoga'),
('Health and Fitness', '#Meditation'),
('Health and Fitness', '#Workout'),
('Health and Fitness', '#Running'),
('Health and Fitness', '#Gym'),
('Health and Fitness', '#Wellness'),
('Health and Fitness', '#MentalHealth'),
('Health and Fitness', '#Diet'),
--- Inspirational and Motivational
('Inspirational and Motivational', '#Motivation'),
('Inspirational and Motivational', '#Inspiration'),
('Inspirational and Motivational', '#Goals'),
('Inspirational and Motivational', '#Success'),
('Inspirational and Motivational', '#Leadership'),
('Inspirational and Motivational', '#HardWork'),
('Inspirational and Motivational', '#DreamBig'),
('Inspirational and Motivational', '#StayPositive'),
('Inspirational and Motivational', '#NeverGiveUp'),
('Inspirational and Motivational', '#SelfImprovement'),
-- Travel and Exploration
('Travel and Exploration', '#SoloTravel'),
('Travel and Exploration', '#CulturalTrips'),
('Travel and Exploration', '#EcoTourism'),
('Travel and Exploration', '#LuxuryTravel'),
('Travel and Exploration', '#Backpacking'),
('Travel and Exploration', '#RoadTrips'),
('Travel and Exploration', '#IslandHopping'),
('Travel and Exploration', '#CityAdventures'),
('Travel and Exploration', '#TravelTips'),
('Travel and Exploration', '#WorldWonders'),
-- Books and Literature
('Books and Literature', '#BookLovers'),
('Books and Literature', '#Fiction'),
('Books and Literature', '#Poetry'),
('Books and Literature', '#ClassicBooks'),
('Books and Literature', '#NonFiction'),
('Books and Literature', '#MysteryNovels'),
('Books and Literature', '#FantasyBooks'),
('Books and Literature', '#Biography'),
('Books and Literature', '#BookClub'),
('Books and Literature', '#ReadingGoals');